development:
  adapter: mysql
  database: test_develoment
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: test_test
  username: root
  password: 
  host: localhost
    
production:
  adapter: mysql
  database: test_production
  username: root
  password: 
  host: localhost
  